In [26]:
1+1

2

In [27]:
2+2

4

In [3]:
import pandas as pd     
import numpy as np

In [28]:
df= np.arange(0,20).reshape(5,4)
df

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### craeting dataframe

In [29]:
af=pd.DataFrame(data=df,index=["Row1","Row2","Row3","Row4","Row5"],
columns=["Column1","Column2","Column3","Column4"])
af

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [25]:
type(af)

pandas.core.frame.DataFrame

In [30]:
af.head(2)        ## top n values

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [31]:
af.tail(2)                       ####last n values

Column1  Column2  Column3  Column4
Row4       12       13       14       15
Row5       16       17       18       19

In [32]:
af.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [41]:
af[["Column1","Column2","Column3"]]


Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [42]:
type(af[["Column1","Column2","Column3"]])

pandas.core.frame.DataFrame

In [44]:
af["Column1"]

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [45]:
type(af["Column1"])

pandas.core.series.Series

In [47]:
af.loc[['Row1','Row2']]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [48]:
af.iloc[0:3,0:2]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9

In [53]:
af.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [9]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4],[5,4,3]],index=["Row1",
                                                      "Row2","Row3"],columns=["Column1",
                                                                             "Column2",
                                                                             "Column3",
                                                                             ])
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [4]:
df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False
Row3    False    False    False

In [10]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [11]:
df.isna().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Row1 to Row3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Column1  3 non-null      int64  
 1   Column2  2 non-null      float64
 2   Column3  3 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 204.0+ bytes


In [13]:
df['Column1'].value_counts()

Column1
1    2
5    1
Name: count, dtype: int64

In [15]:
df['Column1'].unique()

array([1, 5], dtype=int64)

In [20]:
df.nunique(axis=0)

Column1    2
Column2    2
Column3    3
dtype: int64

In [21]:
df.nunique(axis=1)

Row1    2
Row2    3
Row3    3
dtype: int64

In [30]:
af

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [38]:
af[af['Column2']>5]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [44]:
af[af.isna()]

Column1  Column2  Column3  Column4
Row1      NaN      NaN      NaN      NaN
Row2      NaN      NaN      NaN      NaN
Row3      NaN      NaN      NaN      NaN
Row4      NaN      NaN      NaN      NaN
Row5      NaN      NaN      NaN      NaN

In [45]:
af.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [54]:
af.to_csv('test.csv',index=False)

In [55]:
af1=pd.read_csv('test.csv')
af1

Column1  Column2  Column3  Column4
0        0        1        2        3
1        4        5        6        7
2        8        9       10       11
3       12       13       14       15
4       16       17       18       19

In [64]:
af2=af.to_excel('test.xlsx')
af2

In [65]:
af2=pd.read_excel('test.xlsx')
af2

Unnamed: 0  Column1  Column2  Column3  Column4
0       Row1        0        1        2        3
1       Row2        4        5        6        7
2       Row3        8        9       10       11
3       Row4       12       13       14       15
4       Row5       16       17       18       19

In [5]:
data='{"employee_name":"aman","email":"aman@gmail.com","job_profile":[{"title":"data scientist","role":"backend Developer"}]}'
data

'{"employee_name":"aman","email":"aman@gmail.com","job_profile":[{"title":"data scientist","role":"backend Developer"}]}'

In [68]:
af3=pd.read_json(data)
af3

employee_name           email  \
0          aman  aman@gmail.com   

                                         job_profile  
0  {'title': 'data scientist', 'role': 'backend D...

In [69]:
af3=pd.read_json(data,orient='records')

In [70]:
af3

employee_name           email  \
0          aman  aman@gmail.com   

                                         job_profile  
0  {'title': 'data scientist', 'role': 'backend D...

In [71]:
af3=pd.read_json(data,orient='index')
af3

0
employee_name                                               aman
email                                             aman@gmail.com
job_profile    [{'title': 'data scientist', 'role': 'backend ...

In [6]:
af3=pd.read_json(data,orient='column')
af3

employee_name           email  \
0          aman  aman@gmail.com   

                                         job_profile  
0  {'title': 'data scientist', 'role': 'backend D...